import { NextRequest } from "next/server";
import { InstanceRow } from "@/types/api";

export async function GET(req: NextRequest) {
  const sp = req.nextUrl.searchParams;
  const region = sp.get("region") || "us-east-1";

  // Mock data for testing without AWS credentials
  const mockInstances: InstanceRow[] = [
    {
      instanceId: "i-1234567890abcdef0",
      name: "web-server-prod-01",
      region: region,
      availabilityZone: `${region}a`,
      state: "running",
      instanceType: "t3.medium",
      launchTime: "2024-01-15T10:30:00.000Z",
      tags: {
        Environment: "production",
        Team: "frontend",
        Project: "web-app",
        Backup: "enabled",
      },
      costPerHourUsd: 0.0416,
      cpuUtilizationAvg24h: 45.2,
      cpuUtilizationMax24h: 78.9,
      memoryUtilizationAvg24h: 62.1,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-0987654321fedcba0",
      name: "database-master",
      region: region,
      availabilityZone: `${region}b`,
      state: "running",
      instanceType: "r5.large",
      launchTime: "2024-01-10T08:15:00.000Z",
      tags: {
        Environment: "production",
        Team: "backend",
        Project: "database",
        Backup: "enabled",
      },
      costPerHourUsd: 0.126,
      cpuUtilizationAvg24h: 23.7,
      cpuUtilizationMax24h: 45.2,
      memoryUtilizationAvg24h: 89.3,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-1122334455667788",
      name: "batch-processor-01",
      region: region,
      availabilityZone: `${region}c`,
      state: "stopped",
      instanceType: "c5.xlarge",
      launchTime: "2024-01-20T14:00:00.000Z",
      tags: {
        Environment: "staging",
        Team: "data",
        Project: "batch-jobs",
        AutoStop: "true",
      },
      costPerHourUsd: 0.17,
      cpuUtilizationAvg24h: null,
      cpuUtilizationMax24h: null,
      memoryUtilizationAvg24h: null,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [
        {
          reason: "Stopped instance still incurring EBS cost",
          severity: "medium",
        },
      ],
    },
    {
      instanceId: "i-9988776655443322",
      name: "dev-test-server",
      region: region,
      availabilityZone: `${region}a`,
      state: "running",
      instanceType: "t3.micro",
      launchTime: "2024-01-25T09:00:00.000Z",
      tags: {
        Environment: "development",
        Team: "qa",
        Project: "testing",
        AutoStop: "true",
      },
      costPerHourUsd: 0.0104,
      cpuUtilizationAvg24h: 3.2,
      cpuUtilizationMax24h: 12.8,
      memoryUtilizationAvg24h: 18.5,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [
        {
          reason: "CPU < 5% avg (24h)",
          severity: "high",
        },
      ],
    },
    {
      instanceId: "i-5566778899aabbcc",
      name: "ml-training-gpu",
      region: region,
      availabilityZone: `${region}b`,
      state: "running",
      instanceType: "p3.2xlarge",
      launchTime: "2024-01-18T16:00:00.000Z",
      tags: {
        Environment: "production",
        Team: "ml",
        Project: "model-training",
        GPU: "v100",
      },
      costPerHourUsd: 3.06,
      cpuUtilizationAvg24h: 67.8,
      cpuUtilizationMax24h: 95.2,
      memoryUtilizationAvg24h: 74.3,
      gpuUtilizationAvg24h: 89.7,
      wasteIndicators: [],
    },
    {
      instanceId: "i-aabbccddeeff1122",
      name: "monitoring-server",
      region: region,
      availabilityZone: `${region}c`,
      state: "running",
      instanceType: "t3.small",
      launchTime: "2024-01-12T11:00:00.000Z",
      tags: {
        Environment: "production",
        Team: "devops",
        Project: "monitoring",
        Backup: "enabled",
      },
      costPerHourUsd: 0.0208,
      cpuUtilizationAvg24h: 28.9,
      cpuUtilizationMax24h: 56.4,
      memoryUtilizationAvg24h: 41.2,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-1a2b3c4d5e6f7890",
      name: "web-server-prod-02",
      region: region,
      availabilityZone: `${region}a`,
      state: "running",
      instanceType: "t3.medium",
      launchTime: "2024-01-15T10:45:00.000Z",
      tags: {
        Environment: "production",
        Team: "frontend",
        Project: "web-app",
        Backup: "enabled",
      },
      costPerHourUsd: 0.0416,
      cpuUtilizationAvg24h: 52.8,
      cpuUtilizationMax24h: 82.1,
      memoryUtilizationAvg24h: 68.3,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-2b3c4d5e6f7a8901",
      name: "api-gateway-prod",
      region: region,
      availabilityZone: `${region}b`,
      state: "running",
      instanceType: "c5.large",
      launchTime: "2024-01-08T14:20:00.000Z",
      tags: {
        Environment: "production",
        Team: "backend",
        Project: "api-gateway",
        Backup: "enabled",
      },
      costPerHourUsd: 0.085,
      cpuUtilizationAvg24h: 34.7,
      cpuUtilizationMax24h: 67.2,
      memoryUtilizationAvg24h: 45.9,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-3c4d5e6f7a890b12",
      name: "cache-redis-01",
      region: region,
      availabilityZone: `${region}c`,
      state: "running",
      instanceType: "r5.xlarge",
      launchTime: "2024-01-09T09:30:00.000Z",
      tags: {
        Environment: "production",
        Team: "backend",
        Project: "caching",
        Backup: "enabled",
      },
      costPerHourUsd: 0.252,
      cpuUtilizationAvg24h: 18.3,
      cpuUtilizationMax24h: 38.7,
      memoryUtilizationAvg24h: 76.4,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-4d5e6f7a890b1c23",
      name: "log-aggregator",
      region: region,
      availabilityZone: `${region}a`,
      state: "running",
      instanceType: "m5.large",
      launchTime: "2024-01-11T13:15:00.000Z",
      tags: {
        Environment: "production",
        Team: "devops",
        Project: "logging",
        Backup: "enabled",
      },
      costPerHourUsd: 0.096,
      cpuUtilizationAvg24h: 41.2,
      cpuUtilizationMax24h: 73.5,
      memoryUtilizationAvg24h: 58.7,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-5e6f7a890b1c2d34",
      name: "staging-web-01",
      region: region,
      availabilityZone: `${region}b`,
      state: "running",
      instanceType: "t3.small",
      launchTime: "2024-01-22T11:00:00.000Z",
      tags: {
        Environment: "staging",
        Team: "frontend",
        Project: "web-app",
        AutoStop: "true",
      },
      costPerHourUsd: 0.0208,
      cpuUtilizationAvg24h: 12.4,
      cpuUtilizationMax24h: 28.9,
      memoryUtilizationAvg24h: 31.2,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [
        {
          reason: "Low utilization in staging",
          severity: "low",
        },
      ],
    },
    {
      instanceId: "i-6f7a890b1c2d3e45",
      name: "data-warehouse",
      region: region,
      availabilityZone: `${region}c`,
      state: "running",
      instanceType: "r5.4xlarge",
      launchTime: "2024-01-05T07:00:00.000Z",
      tags: {
        Environment: "production",
        Team: "data",
        Project: "analytics",
        Backup: "enabled",
      },
      costPerHourUsd: 1.008,
      cpuUtilizationAvg24h: 56.8,
      cpuUtilizationMax24h: 89.3,
      memoryUtilizationAvg24h: 82.1,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-7a890b1c2d3e4f56",
      name: "backup-server",
      region: region,
      availabilityZone: `${region}a`,
      state: "stopped",
      instanceType: "t3.medium",
      launchTime: "2024-01-16T20:00:00.000Z",
      tags: {
        Environment: "production",
        Team: "devops",
        Project: "backup",
        AutoStop: "true",
      },
      costPerHourUsd: 0.0416,
      cpuUtilizationAvg24h: null,
      cpuUtilizationMax24h: null,
      memoryUtilizationAvg24h: null,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [
        {
          reason: "Stopped instance still incurring EBS cost",
          severity: "medium",
        },
      ],
    },
    {
      instanceId: "i-890b1c2d3e4f5a67",
      name: "ml-inference-01",
      region: region,
      availabilityZone: `${region}b`,
      state: "running",
      instanceType: "p2.xlarge",
      launchTime: "2024-01-19T15:30:00.000Z",
      tags: {
        Environment: "production",
        Team: "ml",
        Project: "inference",
        GPU: "k80",
      },
      costPerHourUsd: 0.9,
      cpuUtilizationAvg24h: 45.7,
      cpuUtilizationMax24h: 76.3,
      memoryUtilizationAvg24h: 67.2,
      gpuUtilizationAvg24h: 23.4,
      wasteIndicators: [
        {
          reason: "GPU underutilized",
          severity: "medium",
        },
      ],
    },
    {
      instanceId: "i-90b1c2d3e4f5a678",
      name: "dev-backend-01",
      region: region,
      availabilityZone: `${region}c`,
      state: "running",
      instanceType: "t3.micro",
      launchTime: "2024-01-26T14:30:00.000Z",
      tags: {
        Environment: "development",
        Team: "backend",
        Project: "api-dev",
        AutoStop: "true",
      },
      costPerHourUsd: 0.0104,
      cpuUtilizationAvg24h: 8.7,
      cpuUtilizationMax24h: 22.1,
      memoryUtilizationAvg24h: 24.5,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-0b1c2d3e4f5a6789",
      name: "elasticsearch-01",
      region: region,
      availabilityZone: `${region}a`,
      state: "running",
      instanceType: "m5.2xlarge",
      launchTime: "2024-01-07T12:00:00.000Z",
      tags: {
        Environment: "production",
        Team: "backend",
        Project: "search",
        Backup: "enabled",
      },
      costPerHourUsd: 0.384,
      cpuUtilizationAvg24h: 67.3,
      cpuUtilizationMax24h: 91.2,
      memoryUtilizationAvg24h: 79.8,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-b1c2d3e4f5a67890",
      name: "queue-worker-01",
      region: region,
      availabilityZone: `${region}b`,
      state: "running",
      instanceType: "c5.2xlarge",
      launchTime: "2024-01-13T16:45:00.000Z",
      tags: {
        Environment: "production",
        Team: "backend",
        Project: "message-queue",
        Backup: "enabled",
      },
      costPerHourUsd: 0.34,
      cpuUtilizationAvg24h: 73.2,
      cpuUtilizationMax24h: 96.7,
      memoryUtilizationAvg24h: 61.4,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-1c2d3e4f5a678901",
      name: "file-storage",
      region: region,
      availabilityZone: `${region}c`,
      state: "running",
      instanceType: "i3.large",
      launchTime: "2024-01-14T10:15:00.000Z",
      tags: {
        Environment: "production",
        Team: "backend",
        Project: "file-system",
        Backup: "enabled",
      },
      costPerHourUsd: 0.156,
      cpuUtilizationAvg24h: 21.8,
      cpuUtilizationMax24h: 43.6,
      memoryUtilizationAvg24h: 38.9,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-2d3e4f5a67890123",
      name: "test-automation",
      region: region,
      availabilityZone: `${region}a`,
      state: "stopped",
      instanceType: "c5.large",
      launchTime: "2024-01-23T09:30:00.000Z",
      tags: {
        Environment: "testing",
        Team: "qa",
        Project: "automation",
        AutoStop: "true",
      },
      costPerHourUsd: 0.085,
      cpuUtilizationAvg24h: null,
      cpuUtilizationMax24h: null,
      memoryUtilizationAvg24h: null,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [
        {
          reason: "Stopped instance still incurring EBS cost",
          severity: "medium",
        },
      ],
    },
    {
      instanceId: "i-3e4f5a6789012345",
      name: "cdn-edge-01",
      region: region,
      availabilityZone: `${region}b`,
      state: "running",
      instanceType: "t3.nano",
      launchTime: "2024-01-21T08:00:00.000Z",
      tags: {
        Environment: "production",
        Team: "frontend",
        Project: "cdn",
        Backup: "disabled",
      },
      costPerHourUsd: 0.0052,
      cpuUtilizationAvg24h: 4.2,
      cpuUtilizationMax24h: 11.8,
      memoryUtilizationAvg24h: 15.7,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [
        {
          reason: "CPU < 5% avg (24h)",
          severity: "high",
        },
      ],
    },
    {
      instanceId: "i-4f5a678901234567",
      name: "security-scanner",
      region: region,
      availabilityZone: `${region}c`,
      state: "running",
      instanceType: "m5.large",
      launchTime: "2024-01-17T13:20:00.000Z",
      tags: {
        Environment: "production",
        Team: "security",
        Project: "vulnerability-scan",
        Backup: "enabled",
      },
      costPerHourUsd: 0.096,
      cpuUtilizationAvg24h: 38.6,
      cpuUtilizationMax24h: 68.9,
      memoryUtilizationAvg24h: 52.3,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-5a67890123456789",
      name: "ml-preprocessing",
      region: region,
      availabilityZone: `${region}a`,
      state: "running",
      instanceType: "r5.2xlarge",
      launchTime: "2024-01-06T11:45:00.000Z",
      tags: {
        Environment: "production",
        Team: "ml",
        Project: "data-prep",
        Backup: "enabled",
      },
      costPerHourUsd: 0.504,
      cpuUtilizationAvg24h: 62.4,
      cpuUtilizationMax24h: 87.1,
      memoryUtilizationAvg24h: 91.3,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-678901234567890a",
      name: "staging-db-replica",
      region: region,
      availabilityZone: `${region}b`,
      state: "running",
      instanceType: "r5.large",
      launchTime: "2024-01-24T15:00:00.000Z",
      tags: {
        Environment: "staging",
        Team: "backend",
        Project: "database",
        AutoStop: "true",
      },
      costPerHourUsd: 0.126,
      cpuUtilizationAvg24h: 9.2,
      cpuUtilizationMax24h: 18.7,
      memoryUtilizationAvg24h: 34.8,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [
        {
          reason: "Oversized for staging workload",
          severity: "medium",
        },
      ],
    },
    {
      instanceId: "i-78901234567890ab",
      name: "ci-build-server",
      region: region,
      availabilityZone: `${region}c`,
      state: "running",
      instanceType: "c5.4xlarge",
      launchTime: "2024-01-12T07:30:00.000Z",
      tags: {
        Environment: "production",
        Team: "devops",
        Project: "ci-cd",
        Backup: "enabled",
      },
      costPerHourUsd: 0.68,
      cpuUtilizationAvg24h: 29.3,
      cpuUtilizationMax24h: 98.4,
      memoryUtilizationAvg24h: 43.7,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [
        {
          reason: "Underutilized most of the day",
          severity: "medium",
        },
      ],
    },
    {
      instanceId: "i-8901234567890abc",
      name: "metrics-collector",
      region: region,
      availabilityZone: `${region}a`,
      state: "running",
      instanceType: "t3.medium",
      launchTime: "2024-01-20T12:15:00.000Z",
      tags: {
        Environment: "production",
        Team: "devops",
        Project: "metrics",
        Backup: "enabled",
      },
      costPerHourUsd: 0.0416,
      cpuUtilizationAvg24h: 35.8,
      cpuUtilizationMax24h: 59.2,
      memoryUtilizationAvg24h: 47.6,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
    {
      instanceId: "i-901234567890abcd",
      name: "dev-frontend-01",
      region: region,
      availabilityZone: `${region}b`,
      state: "stopped",
      instanceType: "t3.small",
      launchTime: "2024-01-27T10:00:00.000Z",
      tags: {
        Environment: "development",
        Team: "frontend",
        Project: "web-dev",
        AutoStop: "true",
      },
      costPerHourUsd: 0.0208,
      cpuUtilizationAvg24h: null,
      cpuUtilizationMax24h: null,
      memoryUtilizationAvg24h: null,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [
        {
          reason: "Stopped instance still incurring EBS cost",
          severity: "medium",
        },
      ],
    },
    {
      instanceId: "i-01234567890abcde",
      name: "database-backup",
      region: region,
      availabilityZone: `${region}c`,
      state: "running",
      instanceType: "r5.xlarge",
      launchTime: "2024-01-04T06:00:00.000Z",
      tags: {
        Environment: "production",
        Team: "backend",
        Project: "backup",
        Backup: "enabled",
      },
      costPerHourUsd: 0.252,
      cpuUtilizationAvg24h: 14.7,
      cpuUtilizationMax24h: 31.8,
      memoryUtilizationAvg24h: 26.4,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [
        {
          reason: "Oversized for backup workload",
          severity: "medium",
        },
      ],
    },
    {
      instanceId: "i-1234567890abcdef",
      name: "analytics-spark",
      region: region,
      availabilityZone: `${region}a`,
      state: "running",
      instanceType: "r5.8xlarge",
      launchTime: "2024-01-03T14:30:00.000Z",
      tags: {
        Environment: "production",
        Team: "data",
        Project: "big-data",
        Backup: "enabled",
      },
      costPerHourUsd: 2.016,
      cpuUtilizationAvg24h: 81.3,
      cpuUtilizationMax24h: 97.6,
      memoryUtilizationAvg24h: 88.9,
      gpuUtilizationAvg24h: null,
      wasteIndicators: [],
    },
  ];

  // Filter by region if specified
  const filteredInstances =
    region === "all"
      ? mockInstances
      : mockInstances.filter((instance) => instance.region === region);

  return Response.json({ instances: filteredInstances });
}
